language: node_js
node_js:
  - "0.10"
  - "0.11"

env:
  global:
    - POSTGRES_HOST=localhost
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_DATABASE=test
    - POSTGRES_PASSWORD=

addons:
  postgresql: "9.3"

notifications:
  email: false

before_script:
  - wget http://sourceforge.net/projects/postbooks/files/03%20PostBooks-databases/4.6.0/postbooks_demo-4.6.0.backup/download -O postbooks_demo_460.backup
  - psql -c 'create database test;' -U postgres
  - psql -c 'create role xtrole;' -U postgres
  - psql -c 'create role admin;' -U postgres
  - pg_restore -e -d test postbooks_demo_460.backup

after_success:
  - head -n 500 build/postbooks_demo_460.json

after_failure:
  - env

deploy:
  - provider: npm
    email: me@traviswebb.com
    api_key:
      secure: KRPpf+/iv3FJBYboRyq7CmRsG7mda8/JG8udUj/bmWIopCW3/hvKxa3rkpZX9gYfshk0Lw7vS/k6LikoTb7l6mOX2HqxnLxvdAaTYruVFRGT0LRJ0nOzZK+WbL7inkoh2S3C/RTwZmPKooYFIlJDpUn6zKANQgdLwnGrgxaXgNg=
    on:
      all_branches: true
  - provider: releases
    api_key:
      secure: GghGojfPthF4XPSyYdQ7nRKIK5Q9lpmrRhJ0zzWGx8cS8o+KxFZ7BgMFXr2Xm9OhZBCDtJJ0YVSJ9Kx2QtOrsU4TG86gkZUR2v7DLd+vRfqYP4kYMe1NsG8ndrWzKGIQnroPi4cDg7H+O+0eGfNzE8hl6l43FD5TJyHsZfnEkLE=
    file: build/postbooks_demo_460.json
    on:
      repo: tjwebb/pg-json-schema-export
      all_branches: true
      tags: true

